import { createContext, useContext, useState } from 'react'

const LangContext = createContext()

const translations = {
  fr: {
    // Nav
    contact: 'Nous contacter',
    // Hero
    heroBadge: "La plateforme #1 de gestion d'avis",
    heroTitle1: 'Transformez vos clients',
    heroTitle2: 'en ',
    heroTitle3: 'ambassadeurs',
    heroSubtitle: "Motivez vos clients satisfaits à partager leur expérience sur Google. Plus d'avis, plus de visibilité, plus de nouveaux clients.",
    heroCta: 'Découvrir comment',
    heroDemo: 'Demander une démo',
    statReviews: "d'avis en moyenne",
    statRating: 'note moyenne obtenue',
    statSetup: 'pour configurer',
    // How it works
    howLabel: 'Simple et efficace',
    howTitle: 'Comment ça marche ?',
    step1Title: 'Scannez le QR code',
    step1Text: 'Placez un QR code dans votre établissement. Le client le scanne avec son téléphone.',
    step2Title: 'Laissez un avis Google',
    step2Text: "Le client est redirigé vers votre fiche Google Maps pour partager son expérience.",
    step3Title: 'Validez et récompensez',
    step3Text: "Vérifiez l'avis dans votre panneau admin et générez un coupon en un clic.",
    // Benefits
    benefitsLabel: 'Vos avantages',
    benefitsTitle: 'Pourquoi nous choisir ?',
    b1Title: 'Augmentez vos avis Google',
    b1Text: "Nos clients constatent en moyenne +300% d'avis dans les 3 premiers mois.",
    b2Title: 'Installation clé en main',
    b2Text: "Aucune compétence technique requise. On s'occupe de tout pour vous.",
    b3Title: 'Récompenses personnalisées',
    b3Text: "Réduction, café offert, coupe gratuite... vous choisissez ce qui convient à votre activité.",
    b4Title: 'Tableau de bord complet',
    b4Text: 'Suivez vos avis, gérez les coupons, et analysez vos performances en temps réel.',
    b5Title: 'Sécurisé et fiable',
    b5Text: "Validation manuelle de chaque avis. Aucun faux avis n'est récompensé.",
    b6Title: 'Multi-établissements',
    b6Text: 'Gérez plusieurs salons ou points de vente depuis une seule plateforme.',
    // Testimonials
    testimonialsLabel: 'Ils nous font confiance',
    testimonialsTitle: 'Ce que disent nos clients',
    t1Text: "\"En un mois, nous sommes passés de 12 à 47 avis Google. L'impact sur notre visibilité est incroyable.\"",
    t1Name: 'Sophie M.',
    t1Role: 'Salon de coiffure, Paris',
    t2Text: '"Mes clients adorent recevoir un petit cadeau après leur avis. C\'est gagnant-gagnant !"',
    t2Name: 'Marc D.',
    t2Role: 'Restaurant, Lyon',
    t3Text: '"La mise en place a pris 5 minutes. Le panneau admin est super intuitif."',
    t3Name: 'Laura K.',
    t3Role: 'Institut de beauté, Marseille',
    // CTA
    ctaTitle: 'Prêt à booster vos avis ?',
    ctaSubtitle: 'Rejoignez les entreprises qui utilisent ReviewValidator pour développer leur réputation en ligne.',
    ctaButton: 'Contactez-nous',
    // Footer
    rights: 'Tous droits réservés.',
    // Mockup
    mockupSalon: 'Mon Salon',
    mockupText: 'Laissez un avis et recevez votre récompense !',
    mockupBtn: 'Écrire un avis',
    mockupReward: 'Votre récompense',
    mockupCouponHint: 'Présentez ce coupon en caisse',
    // Salon pages
    loginSubtitle: 'Connectez-vous pour laisser un avis et recevoir',
    loginButton: 'Se connecter avec Google',
    loginError: 'Erreur de connexion. Réessayez.',
    logout: 'Déconnexion',
    writeReview: 'Écrire un avis',
    writeReviewHint: 'Laissez-nous un avis sur Google et recevez',
    qrHint: 'Pour revenir après avoir ajouté un avis, scannez le QR code à nouveau.',
    pending: "Votre demande est en cours de vérification. Vous recevrez votre coupon une fois l'avis validé par notre équipe.",
    couponTitle: 'Votre récompense',
    couponText: 'Merci pour votre avis ! Présentez ce coupon en caisse pour recevoir',
    couponCopy: 'cliquez pour copier',
    couponCopied: 'Code copié !',
    couponNote: "Coupon à usage unique. Valable jusqu'à révocation.",
    used: 'Votre coupon a déjà été utilisé. Merci pour votre avis !',
    rejected: "Votre demande a été refusée. Veuillez vérifier que vous avez bien laissé un avis sur Google Maps.",
    blocked: "Un coupon a déjà été généré pour ce compte. Il n'est pas possible d'en générer un autre.",
    notFound: "Ce salon n'existe pas ou n'est plus disponible.",
    salonNotFound: 'Salon introuvable',
    error: 'Une erreur est survenue. Veuillez réessayer.',
    // Admin
    admin: 'Administration',
    all: 'Tous',
    tabPending: 'En attente',
    tabApproved: 'Approuvés',
    tabRejected: 'Refusés',
    searchPlaceholder: 'Rechercher par nom, email ou code coupon…',
    refresh: 'Rafraîchir la liste',
    noResults: 'Aucun résultat.',
    noEntries: 'Aucune entrée.',
    colUser: 'Utilisateur',
    colEmail: 'Email',
    colDate: 'Date',
    colStatus: 'Statut',
    colCoupon: 'Coupon',
    colUsed: 'Utilisé',
    colUsedDate: "Date d'utilisation",
    colActions: 'Actions',
    approve: 'Approuver',
    reject: 'Refuser',
    markUsed: 'Marquer utilisé',
    confirm: 'Confirmer',
    cancel: 'Annuler',
    badgeUsed: 'Utilisé',
    statsUsed: 'Utilisés',
  },
  en: {
    contact: 'Contact us',
    heroBadge: 'The #1 review management platform',
    heroTitle1: 'Turn your customers',
    heroTitle2: 'into ',
    heroTitle3: 'ambassadors',
    heroSubtitle: 'Motivate your satisfied customers to share their experience on Google. More reviews, more visibility, more new customers.',
    heroCta: 'Discover how',
    heroDemo: 'Request a demo',
    statReviews: 'more reviews on average',
    statRating: 'average rating obtained',
    statSetup: 'to set up',
    howLabel: 'Simple and effective',
    howTitle: 'How does it work?',
    step1Title: 'Scan the QR code',
    step1Text: 'Place a QR code in your establishment. The customer scans it with their phone.',
    step2Title: 'Leave a Google review',
    step2Text: 'The customer is redirected to your Google Maps listing to share their experience.',
    step3Title: 'Validate and reward',
    step3Text: 'Check the review in your admin panel and generate a coupon in one click.',
    benefitsLabel: 'Your benefits',
    benefitsTitle: 'Why choose us?',
    b1Title: 'Increase your Google reviews',
    b1Text: 'Our clients see an average of +300% reviews in the first 3 months.',
    b2Title: 'Turnkey setup',
    b2Text: 'No technical skills required. We take care of everything for you.',
    b3Title: 'Custom rewards',
    b3Text: 'Discount, free coffee, free haircut... you decide what suits your business.',
    b4Title: 'Complete dashboard',
    b4Text: 'Track your reviews, manage coupons, and analyze your performance in real time.',
    b5Title: 'Secure and reliable',
    b5Text: 'Manual validation of each review. No fake review is rewarded.',
    b6Title: 'Multi-location',
    b6Text: 'Manage multiple salons or points of sale from a single platform.',
    testimonialsLabel: 'They trust us',
    testimonialsTitle: 'What our clients say',
    t1Text: '"In one month, we went from 12 to 47 Google reviews. The impact on our visibility is incredible."',
    t1Name: 'Sophie M.',
    t1Role: 'Hair salon, Paris',
    t2Text: '"My customers love receiving a small gift after their review. It\'s a win-win!"',
    t2Name: 'Marc D.',
    t2Role: 'Restaurant, Lyon',
    t3Text: '"Setup took 5 minutes. The admin panel is super intuitive."',
    t3Name: 'Laura K.',
    t3Role: 'Beauty salon, Marseille',
    ctaTitle: 'Ready to boost your reviews?',
    ctaSubtitle: 'Join the businesses using ReviewValidator to grow their online reputation.',
    ctaButton: 'Contact us',
    rights: 'All rights reserved.',
    mockupSalon: 'My Salon',
    mockupText: 'Leave a review and get your reward!',
    mockupBtn: 'Write a review',
    mockupReward: 'Your reward',
    mockupCouponHint: 'Show this coupon at checkout',
    loginSubtitle: 'Sign in to leave a review and receive',
    loginButton: 'Sign in with Google',
    loginError: 'Connection error. Try again.',
    logout: 'Log out',
    writeReview: 'Write a review',
    writeReviewHint: 'Leave us a Google review and receive',
    qrHint: 'To return after leaving a review, scan the QR code again.',
    pending: 'Your request is being reviewed. You will receive your coupon once the review is validated by our team.',
    couponTitle: 'Your reward',
    couponText: 'Thank you for your review! Show this coupon at checkout to receive',
    couponCopy: 'click to copy',
    couponCopied: 'Code copied!',
    couponNote: 'Single-use coupon. Valid until revoked.',
    used: 'Your coupon has already been used. Thank you for your review!',
    rejected: 'Your request was declined. Please verify that you have left a review on Google Maps.',
    blocked: 'A coupon has already been generated for this account. It is not possible to generate another one.',
    notFound: 'This salon does not exist or is no longer available.',
    salonNotFound: 'Salon not found',
    error: 'An error occurred. Please try again.',
    admin: 'Administration',
    all: 'All',
    tabPending: 'Pending',
    tabApproved: 'Approved',
    tabRejected: 'Rejected',
    searchPlaceholder: 'Search by name, email or coupon code…',
    refresh: 'Refresh list',
    noResults: 'No results.',
    noEntries: 'No entries.',
    colUser: 'User',
    colEmail: 'Email',
    colDate: 'Date',
    colStatus: 'Status',
    colCoupon: 'Coupon',
    colUsed: 'Used',
    colUsedDate: 'Date used',
    colActions: 'Actions',
    approve: 'Approve',
    reject: 'Reject',
    markUsed: 'Mark used',
    confirm: 'Confirm',
    cancel: 'Cancel',
    badgeUsed: 'Used',
    statsUsed: 'Used',
  },
  pl: {
    contact: 'Kontakt',
    heroBadge: 'Platforma #1 do zarządzania opiniami',
    heroTitle1: 'Zmień swoich klientów',
    heroTitle2: 'w ',
    heroTitle3: 'ambasadorów',
    heroSubtitle: 'Zachęć zadowolonych klientów do dzielenia się opinią na Google. Więcej opinii, większa widoczność, więcej nowych klientów.',
    heroCta: 'Dowiedz się jak',
    heroDemo: 'Zamów demo',
    statReviews: 'więcej opinii średnio',
    statRating: 'średnia ocena',
    statSetup: 'na konfigurację',
    howLabel: 'Proste i skuteczne',
    howTitle: 'Jak to działa?',
    step1Title: 'Zeskanuj kod QR',
    step1Text: 'Umieść kod QR w swoim lokalu. Klient skanuje go telefonem.',
    step2Title: 'Wystaw opinię na Google',
    step2Text: 'Klient zostaje przekierowany na Twoją wizytówkę Google Maps.',
    step3Title: 'Zatwierdź i nagradzaj',
    step3Text: 'Sprawdź opinię w panelu admina i wygeneruj kupon jednym kliknięciem.',
    benefitsLabel: 'Twoje korzyści',
    benefitsTitle: 'Dlaczego warto?',
    b1Title: 'Zwiększ liczbę opinii Google',
    b1Text: 'Nasi klienci notują średnio +300% opinii w ciągu pierwszych 3 miesięcy.',
    b2Title: 'Konfiguracja pod klucz',
    b2Text: 'Nie potrzebujesz umiejętności technicznych. Zajmiemy się wszystkim.',
    b3Title: 'Spersonalizowane nagrody',
    b3Text: 'Zniżka, darmowa kawa, darmowe strzyżenie... Ty decydujesz.',
    b4Title: 'Kompletny panel zarządzania',
    b4Text: 'Śledź opinie, zarządzaj kuponami i analizuj wyniki w czasie rzeczywistym.',
    b5Title: 'Bezpieczne i niezawodne',
    b5Text: 'Ręczna weryfikacja każdej opinii. Żadna fałszywa opinia nie zostanie nagrodzona.',
    b6Title: 'Wiele lokalizacji',
    b6Text: 'Zarządzaj wieloma salonami z jednej platformy.',
    testimonialsLabel: 'Zaufali nam',
    testimonialsTitle: 'Co mówią nasi klienci',
    t1Text: '"W ciągu miesiąca przeszliśmy z 12 do 47 opinii Google. Wpływ na naszą widoczność jest niesamowity."',
    t1Name: 'Sophie M.',
    t1Role: 'Salon fryzjerski, Paryż',
    t2Text: '"Moi klienci uwielbiają dostawać mały prezent po wystawieniu opinii. To sytuacja win-win!"',
    t2Name: 'Marc D.',
    t2Role: 'Restauracja, Lyon',
    t3Text: '"Konfiguracja zajęła 5 minut. Panel admina jest bardzo intuicyjny."',
    t3Name: 'Laura K.',
    t3Role: 'Salon kosmetyczny, Marsylia',
    ctaTitle: 'Gotowy, żeby zwiększyć liczbę opinii?',
    ctaSubtitle: 'Dołącz do firm, które używają ReviewValidator do budowania reputacji online.',
    ctaButton: 'Skontaktuj się z nami',
    rights: 'Wszelkie prawa zastrzeżone.',
    mockupSalon: 'Mój Salon',
    mockupText: 'Wystaw opinię i odbierz nagrodę!',
    mockupBtn: 'Napisz opinię',
    mockupReward: 'Twoja nagroda',
    mockupCouponHint: 'Pokaż ten kupon przy kasie',
    loginSubtitle: 'Zaloguj się, aby wystawić opinię i otrzymać',
    loginButton: 'Zaloguj się przez Google',
    loginError: 'Błąd logowania. Spróbuj ponownie.',
    logout: 'Wyloguj się',
    writeReview: 'Napisz opinię',
    writeReviewHint: 'Wystaw nam opinię na Google i otrzymaj',
    qrHint: 'Aby wrócić po wystawieniu opinii, zeskanuj kod QR ponownie.',
    pending: 'Twoje zgłoszenie jest weryfikowane. Otrzymasz kupon po zatwierdzeniu opinii przez nasz zespół.',
    couponTitle: 'Twoja nagroda',
    couponText: 'Dziękujemy za opinię! Pokaż ten kupon przy kasie, aby otrzymać',
    couponCopy: 'kliknij, aby skopiować',
    couponCopied: 'Kod skopiowany!',
    couponNote: 'Kupon jednorazowego użytku. Ważny do odwołania.',
    used: 'Twój kupon został już wykorzystany. Dziękujemy za opinię!',
    rejected: 'Twoje zgłoszenie zostało odrzucone. Sprawdź, czy wystawiłeś opinię na Google Maps.',
    blocked: 'Kupon został już wygenerowany dla tego konta. Nie można wygenerować kolejnego.',
    notFound: 'Ten salon nie istnieje lub nie jest już dostępny.',
    salonNotFound: 'Nie znaleziono salonu',
    error: 'Wystąpił błąd. Spróbuj ponownie.',
    admin: 'Administracja',
    all: 'Wszystkie',
    tabPending: 'Oczekujące',
    tabApproved: 'Zatwierdzone',
    tabRejected: 'Odrzucone',
    searchPlaceholder: 'Szukaj po nazwie, emailu lub kodzie kuponu…',
    refresh: 'Odśwież listę',
    noResults: 'Brak wyników.',
    noEntries: 'Brak wpisów.',
    colUser: 'Użytkownik',
    colEmail: 'Email',
    colDate: 'Data',
    colStatus: 'Status',
    colCoupon: 'Kupon',
    colUsed: 'Użyty',
    colUsedDate: 'Data użycia',
    colActions: 'Akcje',
    approve: 'Zatwierdź',
    reject: 'Odrzuć',
    markUsed: 'Oznacz jako użyty',
    confirm: 'Potwierdź',
    cancel: 'Anuluj',
    badgeUsed: 'Użyty',
    statsUsed: 'Użyte',
  },
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('rv-lang')
    if (saved && translations[saved]) return saved
    const browser = navigator.language.slice(0, 2)
    return translations[browser] ? browser : 'fr'
  })

  const t = translations[lang]

  const changeLang = (newLang) => {
    setLang(newLang)
    localStorage.setItem('rv-lang', newLang)
  }

  return (
    <LangContext.Provider value={{ lang, t, changeLang }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
